/**
    Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

    Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at

        http://aws.amazon.com/apache2.0/

    or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/

module.exports = {
    "playdough": "Ingredients: 1 cup of any flour, one quarter cup of salt, one half cup of water, 3 to 5 drops of natural food coloring.  Instructions: Step 1: Mix together the flour and the salt.  Step 2: Mix together one half cup of warm water with a few drops of food coloring.  Step 3: Slowly, pour the water into the flour mixture, stirring as you pour. Stir until combined. Knead with your hands until the flour is completely absorbed. If the dough is too sticky, add more flour until it doesn’t stick at all.  It is recommended that you keep your play dough in an airtight container.",
    "potato stamps": "Materials: Potatoes, a knife, a chopping board, some non-toxic paint, shallow plates, and paper. Instructions: 1. Clean the potatoes then dry them with a towel. 2. Cut into shapes. There are a few ways to do this. You can cut the potato in half and carve out the shape at the bottom. Or, you can cut the potato into 2inch thick cross sections then carve the entire cross section into the desired shape. 3. Dip a potato stamp in paint, making sure that the bottom is evenly-coated with paint. 4. Have fun stamping!",
    "gak": "Gak is a non-newtonian fluid. Materials: plastic tub or bin, glass bowl, glue, warm water, food coloring, Borax. Instructions: 1. Squeeze about 4 ounces of glue into a glass bowl. 2. Mix in 4 ounces of warm water. 3. Add your food coloring. 4. Mix 1 teaspoon of Borax into 1/2 cup of water, and slowly add the solution to the glue mixture. 5. Stir until the slime starts to come together. You may not use all of the Borax solution. 6.  Knead the gak until it is one easy-to-work-with mass of slime.",
    "kinetic sand": "Ingredients: baking soda, baking powder, dishwashing liquid, a mixing bowl, and a spoon. Instructions: 1. Mix together 2 parts baking soda and 1 part baking powder along with 1 part of dishwashing liquid in a large bowl. 2. Stir the mixture with a spoon until a sandy/doughy substance forms. Keep adding baking powder if the mixture seems too wet. 3. Knead the mixture together until it feels sandy and dough-like but not wet. If you have to, add some more baking powder at this point too in order to make it fluffy. 4. Store in a plastic container to be able to have fun over and over again!",
    "paper mache": "Ingredients: flour and water. Instructions: Pour some white flour in a bowl, and add water gradually until you have a consistency that will work well. Use a small kitchen mixer so you don’t have any lumps. Important things to keep in mind: It is the flour, and not the water, that gives strength to your paper mache sculpture. Remember that each layer of paste and paper that is added to your project must dry completely to keep it from developing mold.",
    "super bouncy ball": "Ingredients: Borax,  warm water, corn starch,  glue,  2 small mixing cups, something to stir with, and food coloring. Instructions: 1. Set out the two mixing cups. 2. Label one cup ‘Borax Solution’ and the other cup ‘Ball Mixture’. 3. Pour 4 ounces of warm water into the cup labeled ‘Borax Solution’ and 1 teaspoon of the borax powder into the cup. Stir the mixture to dissolve the borax. 5.  Pour 1 tablespoon of glue into the cup labeled ‘Ball Mixture’. Add 3-4 drops of food coloring. 5. Add 1/2 teaspoon of the borax solution you just made and 1 tablespoon of cornstarch to the glue. Do not stir. 6. Allow the ingredients to interact on their own for 10-15 seconds and then stir them together to fully mix. 7. Once the mixture becomes impossible to stir, take it out of the cup and start molding the ball with your hands. The ball will start out sticky and messy, but will solidify as you knead it. Once the ball is less sticky, continue rolling between your hands until it is smooth and round! 8. Enjoy your new SUPER BOUNCY BALL!",
    "water-proof sand": "Ingredients: safety glasses, sand (colored crafting sand or sand from a pet store  work really well), metal cake pan, oven, and Scotch Guard. Instructions: 1. Spread a cup of sand onto a metal cake pan, making an even layer of sand. 2. Place the sand into the oven and set it at 200 degrees Fahrenheit for 1 hour to remove any moisture still contained in the sand. 3. Allow the sand to cool completely until it reaches room temperature. 4. With safety glasses and the assistance of an adult, spray the sand with an even coat of Scotch Guard. Make sure your work area is covered with old newspaper or some protective covering. 5. Allow any volatile gases to evaporate off the sand by shaking the sand occasionally for 10-15 minutes. Allow to dry completely (approximately one hour). 6. You're done! You've made hydrophobic sand! Slowly, pour into water and watch what happens.",
    "crystal needles": "Ingredients: cup or small bowl, epsom salt, and hot tap water. Instructions: 1. In a cup or small, deep bowl, mix one half cup of Epsom salt (also called magnesium sulfate) with a half cup of hot tap water. 2. Stir about a minute to dissolve the Epsom salt. There will still be some undissolved crystals at the bottom. 3. Place the cup in the refrigerator. The bowl will fill with needle-like crystals within three hours. Important things to keep in mind: Don’t use boiling water to prepare your solution. You can place a small object at the bottom of the cup to make it easier to remove your crystals, such as a quarter or plastic bottle cap.",
    "ooblek": "Ingredients: cornstarch, a small amount of water, stirring rod or spoon, container, like a disposable pie pan, a measuring spoon. Instructions: 1. Start with the water in a bowl and add the cornstarch a bit at a time. 2. Keep stirring until it has a gooey consistency. Dig in with your hands! 3. Add food coloring if you're feeling silly. Things to do with oo-blek: Squeeze a fistfull. Drag your fingers through a pool of it. Shake it in a plastic cup. Jab it with your finger then slowly push your finger into it. Roll it into a ball then let it sit in the palm of your hand. Put a cookie sheet over a speaker then pour the ooblek on and watch it dance.",
    "potato-powered lightbulb": "Ingredients: A large potato, two pennies, two zinc-plated nails, three pieces of copper wire, and a very small light bulb or LED light. Instructions: Cut the potato in half, then cut a small slit into each half, large enough to slide a penny inside.  Wrap some copper wire around each penny a few times. Use a different piece of wire for each penny.  Stick the pennies in the slits you cut into the potato halves.  Wrap some of the third copper wire around one of the zinc-plated nails and stick the nail into one of the potato halves.  Take the wire connected to the penny in the half of potato with the nail and wrap some of it around the second nail. Stick that second nail into the other potato half.  When you connect the two loose ends of the copper wires to the light bulb or LED it will light up.",
    "secret spy writing": "Ingredients: lemon half, some water, cotton swab, and paper. Instructions: 1. Squeeze the lemon juice from half of a lemon in a bowl. 2. Add a few drops of water into the lemon juice. Stir. 3. With a cotton swab, dab it into the solution and write a message on a piece of paper. 3. Allow the paper to dry. 4. Once dried, hold the paper over a hot light bulb until the message reappears.",
    "rock candy": "Ingredients: 4 cups sugar, 2 cups water, a small saucepan, a wooden spoon, a candy thermometer, a clean glass jar, a measuring cup, cotton string, a weight to hang on the string - such as a screw or galvanized washer, waxed paper, a pencil - to suspend the string in the jar. Instructions: 1. Heat the water in the saucepan until it comes to a boil.  2. Dissolve the sugar in the water, stirring with the wooden spoon until clear and at a roiling boil. 3. Take the solution off the heat, and pour into the glass jar. Cover the jar with the waxed paper.  4. Tie the weight to one end of the string, and then tie the other end to the middle of the pencil. The string should be about two-thirds as long as the jar is deep. Dip the string into the sugar solution, remove it, lay it on a piece of waxed paper, straighten it out, and let it dry for a few days.  5. Suspend the string in the sugar solution and let sit at room temperature, undisturbed, for several days. DO NOT TOUCH THE STRING.  6. At the end of the week, you should have nicely defined crystals.",
    "volcano": "Ingredients: 6 cups flour, 2 cups salt, 4 tablespoons cooking oil, warm water, plastic soda bottle, dishwashing detergent, food coloring, vinegar, baking dish or other pan, 2 T baking soda. Instructions: First make the 'cone' of the baking soda volcano. Mix 6 cups flour, 2 cups salt, 4 tablespoons cooking oil, and 2 cups of water. The resulting mixture should be smooth and firm (more water may be added if needed). 2. Stand the soda bottle in the baking pan and mold the dough around it into a volcano shape. Don't cover the hole or drop dough into it. 3. Fill the bottle most of the way full with warm water and a bit of red food. 4. Add 6 drops of detergent to the bottle contents. 5. Add 2 tablespoons baking soda to the liquid. 6. Slowly pour vinegar into the bottle. BE CAREFUL!",
    "edible glass": "Ingredients: 3 cups sugar, 2/3 cup light corn syrup, 1 teaspoon Cream of Tartar (Or other food grade acid), A candy thermometer, and a source of heat. Instructions: Add sugar and 8 ounces of water to the pot, and put it on what ever heat level you prefer to bring it to a boil, Low has less chance of browning, whilst High Heat is faster...  Add your candy thermometer, and when you solution reaches 230F add you Corn syrup and Tartar, mix is thoroughly, being careful not to splash the side of the pan.After that, all that is left to do is wait for the batch to reach hard crack stage (302F), once that has been achieved remove your pot from heat and submerge the sides into cold water for around 10 seconds, this is to prevent residential heating and accidental browning...  If you do not take it off a cool it at this point, the mixture will probably pass 310F and brown making the glass look unappealing...  If you made the mistake of not paying attention for a few seconds and come back to a browned syrup, all may not be lost, Quickly cool it as I have described above method and let it sit till the temp is down to about 200F. At this point you can add dye of your choice and thoroughly mix in to help hide the discoloration...  Once you feel that it is ready to pour (Needs to still be at least Syrup like consistency) get your mold ready (Should be Lightly Greased to ensure ease of release) pour your molten mixture in a thin stream as high as you can get it so you don't have any bubbles in your glass...  So now, let it cool and eat your glass!"
};
